# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


parameters:
  - name: vnet_mgmt
    default: "himgmt"
  - name: vnet_sap
    default: "hisap"

steps: 
  - ${{ each variable in parameters }}:
    - script: echo ${{ variable.Key }} 
    - script: echo ${{ variable.Value }}