---

# This is temperary solution to get bits from SMP

# Due to the file permission limitation with blob (always 770), we currently only support using azure files.
- name: Install unzip
  apt: 
    name: unzip
    state: latest
    force_apt_get: yes

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/bin/get-pip.py

- name: Install pip for python
  command: |
    python2 /usr/bin/get-pip.py

- name: Install python3-winrm
  apt:
    name: python3-winrm
    state: latest
    force_apt_get: yes

#- name: Install pywinrm
#  pip:
#    name: pywinrm
#    state: latest

- name: test
  register: results
  args:
    stdin: |
        import winrm
        session = winrm.Session('10.0.1.4', auth=('azureadm','Sap@hana2019!'))
        result = session.run_ps("hostname")
        print(result.std_out)
  command: /usr/bin/python
  ignore_errors: true
    
- debug: var=results

- name: Install pip for python3
  command: |
    python3 /usr/bin/get-pip.py

- name: Install beautifulsoup4
  pip:
    name: beautifulsoup4
    state: latest
    executable: pip3

#- name: Download installation media
#  shell: "python3 {{ sap_media_download_script_loc }}/python/downloader/basket.py --config /home/{{ ansible_user}}/output.json --dir {{ azure_files_mount_path }}"

#- name: Identify media archive
#  shell: "ls {{ azure_files_mount_path }}/DB|grep ZIP"
#  register: bits_file

#- name: Extract media archive
#  unarchive: 
#    src: "{{ azure_files_mount_path }}/DB/{{bits_file.stdout}}"
#    dest: "{{ azure_files_mount_path }}/DB"
#    remote_src: yes
